# Generated by Django 5.0.3 on 2024-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
