# Generated by Django 5.0.3 on 2024-03-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_code_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='core.region'),
        ),
        migrations.AlterField(
            model_name='street',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.commune'),
        ),
    ]
