# Generated by Django 5.0.3 on 2024-03-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_region_alter_street_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ong',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='vulnerabilities',
            field=models.ManyToManyField(related_name='peoples', to='core.vulnerability'),
        ),
        migrations.AlterField(
            model_name='street',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='core.commune'),
        ),
    ]
