# Generated by Django 5.0.2 on 2024-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_people_year_in_school_people_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('1', 'Alive'), ('0', 'Dead')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='has_birth_certificat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='has_cni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_handicape',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_menage_chief',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_utochtone',
            field=models.BooleanField(default=False),
        ),
    ]
