FROM python:3.10

WORKDIR /app

# RUN  apt update && apt install python3-dev default-libmysqlclient-dev

COPY ./Pipfile ./Pipfile.lock /app/

RUN pip install pipenv && pipenv install --system

COPY ./ /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:9000"]
