FROM node:20-alpine as development

RUN npm install -g pnpm

WORKDIR /app

COPY ./package.json ./pnpm-lock.yaml  ./

RUN pnpm install

COPY . .

EXPOSE 4400

CMD ["pnpm", "start:dev"]
# CMD ["tail", "-f", "/dev/null"]