FROM node:20-alpine as development

RUN npm install -g pnpm

WORKDIR /app

COPY ./package.json ./pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN npm i -g pnpm  

RUN pnpm install

COPY . .

EXPOSE 4400

CMD ["pnpm", "start:dev"]