# Generated by Django 5.0.2 on 2024-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commune_menage_people_street_vulnerability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
